#travis
language: objective-c
osx_image: xcode7.3

before_install:
- rvm use $RVM_RUBY_VERSION
- gem install slather -N 

install: bundle install --without=documentation --path ../travis_bundle_dir

# script:
# - xctool -project GlipKit.xcodeproj -scheme GlipKit -destination "platform=iOS Simulator,name=iPhone 6" -sdk iphonesimulator clean build test ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES  

after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) -f coverage_report/cobertura.xml
